### ISSUE TITLE
Left over Hyperspy Folder

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/holospy#1]
We might need to delete this repo and try agin :/ Apparently I copied the history for hyperspy-extension.ymal file without knowing it...

@ericpre any advice here?

I think the right git filter is 

```git filter-repo --path holospy/ --path doc/user_guide/electron_holography.rst --path hyperspy/misc/holography/ --path hyperspy/_signals/hologram_image.py --path hyperspy/tests/signals/test_hologram_image.py --path hyperspy/tests/signals/test_hologram_image_statistics.py --path-rename holospy/: --force ```

We could also maybe just force push to the repo and clean things up that way....

**Comment by CSSFrancis** [comment]
I think this is the right commit history https://github.com/CSSFrancis/holospy

**Comment by ericpre** [comment]
Yeah, maybe it needed to exclude `hyeprspy/misc/example_signals` and `hyperspy/hyperspy_extension.yaml` and then force push. I would remove the last merge commit at the same time (reset head to the commit before the merge commit before reunning `git filter-repo`?).

**Comment by ericpre** [comment]
Done in #2.
