### ISSUE TITLE
Making a logo

### ISSUE THREAD

**Issue by jlaehne** [hyperspy/holospy#20]
Following https://github.com/hyperspy/exspy/issues/17 I also played on the possibility of a holoSpy logo, drawing on the idea of having a simplified sketch of the off-axis electron holography setup as 'l' and giving the rest of 'holo' a hologram like appearance:

![holospy](https://github.com/hyperspy/holospy/assets/7076057/738e5540-b041-48af-a771-b84e6d18ecaf)

The last one being my personal favorite, I also made a dark version of it.

**Comment by jlaehne** [comment]
I got some positive feedback from colleagues working with holography for the version at the bottom that also I prefer (I could make the snakehead a bit thicker though).

**Comment by jlaehne** [comment]
Snakehead optimized:
![image](https://github.com/hyperspy/holospy/assets/7076057/a0defae8-7ac5-4f7b-8a24-de1c705dd158)

**Comment by CSSFrancis** [comment]
@jlaehne How do you feel about adding some colors to the logo?  I like the idea of the shadows but I think that currently there is too much and it kind of makes me dizzy :)  I would maybe just do more of a shadow effect. The simplified TEM is pretty cool and I really like that part!

**Comment by jlaehne** [comment]
I wanted to try to mimick the appearance of a hologram. To make it less dizzy, I have for the moment played with a larger shift of the "mirror images". Also, maybe it makes more sense to only have to two 'o' with that effect:

![holospy](https://github.com/hyperspy/holospy/assets/7076057/4a101397-aca8-4a28-8382-dc3e5a0cf3c6)

**Comment by jlaehne** [comment]
Playing with the HyperSpy colors for the microscope/biprism (but personally I prefer the grayscale):

![image](https://github.com/hyperspy/holospy/assets/7076057/b0953629-ac00-447c-aada-0383827a611c)
